### ISSUE TITLE
Measurments improvments in the Airly API

### ISSUE THREAD

**Issue by Mondonno** [airly-eu/api-docs#10]
Hello dear Airly Staff.

It is not issue but a feature request to implement some improvments wich has been relased but it is not.
This feature is implementation to Measurments API object new filed called: installationId. This will give posibbility to for example merge array of matching measurments to array of matching installations iwthout matter. For now it is unpossible beacuse of the fact that the API does not giving developers the locationId where measurment belogns. If it no have any conflicts with the Airly App functional, If you can please implement this it will be so useful 

Regards.
Mondonno

**Comment by Mondonno** [comment]
Any update here?

**Comment by maraswrona** [comment]
Hello @Mondonno 

I'm not sure I understand your message. Currently our API allows querying measurements of individual installations (sensors) only, or interpolating measurements for any point on the map from nearby installations. The `installationId` is not present in `/measurements` response because it is already included in the request path as path parameter. I don't see really any value in adding it to the response.

In any case, please refer to our documentation: https://developer.airly.org/en/docs

Also, this repository is rather to maintain our docs page. Issues should refer to our Developer Portal content (e.g. typos, undocumented features etc). Any API questions or feature requests should be reported to apisupport@airly.org or via contact page: https://airly.org/en/contact/
